import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Reveal } from "./Reveal";

const layers = [
  {
    id: "01",
    title: "LinkedIn Profile",
    description: "Career trajectory, progression, and public professional context.",
    color: "var(--navy)",
  },
  {
    id: "02",
    title: "Resume",
    description: "Formal record of roles, responsibilities, and achievements.",
    color: "var(--crimson)",
  },
  {
    id: "03",
    title: "Recruiter Insights",
    description: "Notes and observations from partner conversations with candidates — covering leadership philosophy, strategic thinking, and commercial orientation. This is the layer that documents do not reach.",
    color: "var(--tangerine)",
  },
  {
    id: "04",
    title: "Client Feedback",
    description: "Where a candidate has previously been presented to a client, feedback from those interactions is stored and used to build a more accurate picture over time.",
    color: "var(--golden)",
  },
  {
    id: "05",
    title: "Competency Map",
    description: "Candidates are assessed against a structured framework. Assessments are generated by xyrus and validated by partners.",
    color: "var(--steel)",
  },
];

export const HowItWorks = () => {
  const [activeLayer, setActiveLayer] = useState<string | null>(null);

  return (
    <section id="how-it-works" className="py-24 md:py-32 section-padding bg-background">
      <div className="max-w-7xl mx-auto">
        <Reveal>
          <span className="font-mono-brand text-xs tracking-[0.3em] text-crimson uppercase">
            How xyrus works
          </span>
        </Reveal>
        <Reveal delay={0.1}>
          <h2 className="text-3xl md:text-4xl lg:text-5xl font-bold text-foreground leading-[1.05] mt-6 max-w-3xl tracking-tight">
            From fragmented data to a{" "}
            <span className="text-crimson">precision shortlist.</span>
          </h2>
        </Reveal>
        <Reveal delay={0.15}>
          <p className="text-base text-muted-foreground leading-relaxed mt-6 max-w-2xl">
            xyrus is XQtiv's 24/7 hiring accelerator. It runs continuously — enriching profiles, updating assessments, and mapping the leadership market in real time. You will have an end-to-end profile of the candidate, before your first interview with them.
          </p>
        </Reveal>

        {/* Five layers interactive */}
        <div className="mt-16">
          <Reveal delay={0.2}>
            <div className="font-mono-brand text-[10px] tracking-[0.3em] text-muted-foreground uppercase mb-8">
              Five Levels of Candidate Intelligence
            </div>
          </Reveal>

          <div className="space-y-[1px]">
            {layers.map((layer, i) => (
              <Reveal key={layer.id} delay={0.25 + i * 0.06}>
                <button
                  onClick={() => setActiveLayer(activeLayer === layer.id ? null : layer.id)}
                  className="w-full text-left group"
                >
                  <div
                    className={`flex items-center gap-6 p-6 rounded-sm transition-all duration-300 border ${
                      activeLayer === layer.id
                        ? "bg-navy border-navy"
                        : "bg-background border-border hover:border-foreground/20"
                    }`}
                  >
                    <span
                      className={`font-mono-brand text-xs tracking-widest ${
                        activeLayer === layer.id ? "text-crimson" : "text-muted-foreground"
                      }`}
                    >
                      {layer.id}
                    </span>
                    <div className="flex-1">
                      <span
                        className={`text-lg font-bold ${
                          activeLayer === layer.id ? "text-primary-foreground" : "text-foreground"
                        }`}
                      >
                        {layer.title}
                      </span>
                    </div>
                    <motion.div
                      animate={{ rotate: activeLayer === layer.id ? 45 : 0 }}
                      transition={{ duration: 0.2 }}
                      className={`text-xl ${
                        activeLayer === layer.id ? "text-crimson" : "text-muted-foreground"
                      }`}
                    >
                      +
                    </motion.div>
                  </div>

                  <AnimatePresence>
                    {activeLayer === layer.id && (
                      <motion.div
                        initial={{ height: 0, opacity: 0 }}
                        animate={{ height: "auto", opacity: 1 }}
                        exit={{ height: 0, opacity: 0 }}
                        transition={{ duration: 0.3, ease: [0.16, 1, 0.3, 1] }}
                        className="overflow-hidden"
                      >
                        <div className="px-6 pb-6 pt-2 bg-navy rounded-b-sm border-x border-b border-navy">
                          <p className="text-steel text-sm leading-relaxed max-w-2xl ml-12">
                            {layer.description}
                          </p>
                        </div>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </button>
              </Reveal>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
};
